version: '3.8'

services:
  # Spring Boot Application
  app:
    image: mehdino123/foyer-spring
    container_name: devopsSpringApp
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/devops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - db
    networks:
      - devops-network

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: devops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"

    networks:
      - devops-network

# Define the networks and volumes
networks:
  devops-network:
    driver: bridge


