apiVersion: apps/v1
kind: Deployment
metadata:
  name: foyer-app
  labels:
    app: foyer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foyer-app
  template:
    metadata:
      labels:
        app: foyer-app
    spec:
      containers:
      - name: foyer-app
        image: moetezmarzouki/foyer-spring:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root" # Replace with your actual MySQL username
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/Foyer"
---
apiVersion: v1
kind: Service
metadata:
  name: foyer-service
  labels:
    app: foyer-app
spec:
  type: NodePort
  selector:
    app: foyer-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32001  # Replace with a suitable port if needed
