apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'spring-boot'
        static_configs:
          - targets: ['foyer-service:8081']

      - job_name: 'mysql'
        static_configs:
          - targets: ['mysql:9104']
